# Generated by Django 6.0.3 on 2026-03-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
